import { StyleSheet } from "react-native";

const AppStyles = StyleSheet.create({
  // General
  container: {
    flex: 1,
    backgroundColor: "#f4f7fb",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f4f7fb",
    paddingHorizontal: 20,
  },
  loadingText: {
    color: "#4a90e2",
    marginTop: 12,
    fontSize: 16,
    fontWeight: "600",
  },

  // Buttons
  favButton: {
    backgroundColor: "#1e88e5",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#1e88e5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  favButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 1,
  },

  searchInput: {
  backgroundColor: "#ffffff",
  borderRadius: 14,
  paddingHorizontal: 16,
  paddingVertical: 14,
  fontSize: 15,
  marginBottom: 16,
  borderWidth: 1,
  borderColor: "#e4e9f0",
  color: "#14213d",
  },

  // Home Screen Cards
  card: {
    backgroundColor: "#ffffff",
    padding: 18,
    borderRadius: 18,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#eef2f7",
  },
  cryptoName: {
    color: "#14213d",
    fontSize: 19,
    fontWeight: "700",
  },
  cryptoSymbol: {
    color: "#7b8794",
    fontSize: 13,
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  cryptoPrice: {
    color: "#1e88e5",
    fontSize: 17,
    marginTop: 8,
    fontWeight: "700",
  },
  cryptoChange: {
    fontSize: 14,
    marginTop: 4,
    fontWeight: "600",
  },

  // Detail Screen
  detailContainer: {
    flex: 1,
    backgroundColor: "#f4f7fb",
    padding: 20,
  },
  detailCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 22,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#eef2f7",
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#14213d",
    marginBottom: 4,
  },
  detailSymbol: {
    fontSize: 14,
    color: "#7b8794",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 18,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#edf2f7",
  },
  detailLabel: {
    fontSize: 14,
    color: "#7b8794",
    fontWeight: "600",
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    color: "#14213d",
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  favouriteButton: {
    backgroundColor: "#1e88e5",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 6,
    marginBottom: 24,
    shadowColor: "#1e88e5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  favouriteButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 1,
  },

  // Favourites Screen
  emptyText: {
    color: "#7b8794",
    fontSize: 17,
    textAlign: "center",
    marginTop: 50,
    fontWeight: "500",
  },
  clearButton: {
    backgroundColor: "#e53935",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#e53935",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
    elevation: 4,
  },
  clearButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 1,
  },
  clearButtonDisabled: {
    backgroundColor: "#c7c7c7",
    shadowOpacity: 0,
    elevation: 0,
  },
  favCard: {
    backgroundColor: "#ffffff",
    padding: 18,
    borderRadius: 18,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#eef2f7",
  },
  favCardName: {
    color: "#14213d",
    fontSize: 17,
    fontWeight: "700",
  },
  favCardSymbol: {
    color: "#7b8794",
    fontSize: 13,
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  deleteButton: {
    backgroundColor: "#fff0f0",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
  },
  deleteButtonText: {
    color: "#e53935",
    fontWeight: "700",
    fontSize: 13,
  },
});

export default AppStyles;